### ISSUE TITLE
OACMPDM2 invisible lights

### ISSUE THREAD

**Issue by The-Gig** [NeonKnightOA/oacmpvol1#10]
Tested with z_oacmp1v4_beta-220322.pk3

OACMPDM2: I found some _invisible bricks_ (weaponclip brushes I guess) around the outer border of the upper floor (in the corners and where you can jump down). Also on the sides of the lower level bridges.
![shot0219](https://user-images.githubusercontent.com/23258514/161791660-0fdb1c72-b1d1-4c30-848e-043404ea460b.jpg)
![shot0216](https://user-images.githubusercontent.com/23258514/161791666-ba9cebd1-77f4-4a6e-b697-16a3f4aca598.jpg)
![shot0217](https://user-images.githubusercontent.com/23258514/161791670-935902ef-c882-482f-a370-7f9e42314529.jpg)
![shot0218](https://user-images.githubusercontent.com/23258514/161791672-6f7b090d-4440-4947-be76-61400e87d0e8.jpg)

**Comment by NeonKnightOA** [comment]
Looks like something messed up. Fixing!

**Comment by The-Gig** [comment]
Checked with oacmpv3: there should be some "lights" there, their models disappeared!
![Screenshot_20220406-073232](https://user-images.githubusercontent.com/23258514/161902786-0cffb787-2933-441c-b761-c183672c27ec.png)

Now that I think about it, maybe you used the same light models also in some other maps (but I don't remember which ones), so we should check them too...

**Comment by NeonKnightOA** [comment]
Then it's indeed a problem.

**Comment by NeonKnightOA** [comment]
Confirmed, the mapmodel wasn't baked in the map and as a result lights don't appear.

**Comment by NeonKnightOA** [comment]
The mapmodel in question is a 0.8.8 mapmodel created for am_spacecont, a simple light source.

**Comment by NeonKnightOA** [comment]
Indeed, the shaders and textures were the problem. Once the power returns, I'll upload the modified stuff.

Fixed.

**Comment by The-Gig** [comment]
Tested the new version of the map, I confirm now the models of the lights are shown.
