### ISSUE TITLE
OACMPDM7 Lightning gun not spawning

### ISSUE THREAD

**Issue by The-Gig** [NeonKnightOA/oacmpvol1#14]
I'm checking old "todo lists" from the forum against z_oacmp1v4_beta-220322.pk3.

OACMPDM7: Lightning gun does not spawn. According to console output, it looks like it's "in solid" and should be moved a bit to be able to spawn. There is an area marked as "weapon spawn" where nothing appears indeed.

**Comment by NeonKnightOA** [comment]
Definitely a problem. I'll check and fix.

**Comment by NeonKnightOA** [comment]
Confirmed and fixed. I'll check all other items in case there's something else in solid.

**Comment by The-Gig** [comment]
> Confirmed and fixed. I'll check all other items in case there's something else in solid.

You know, if they are so much "in solid" _to not be able to spawn_, you can scroll back console output, searching for "<item> in solid/startsolid at (X, Y, Z)" (under "---- Map Loading ----" section and below "AAS initialized"). This check should always be done before publishing any map.

In case the item is just appearing too near to a brush causing it to spawn, but with its model slightly permeating it, then you actually need a visual check to notice it.

**Comment by NeonKnightOA** [comment]
Yeah but still seized the change to see how items were accomodated in the game world. Luckily, only the LG was problematic.

**Comment by The-Gig** [comment]
I tested the new map, and I confirm that LG works now. I see there are a few small bonuses maybe too near each other, like these you can see in this screenshot. But considering they still work, I guess we may consider them "not bugs", what do you think? Let's just hope OA3 will not replace their models with something much larger...
![shot0243](https://user-images.githubusercontent.com/23258514/162436554-a6e71604-5841-4763-8185-1d710ce0e7a7.jpg)

**Comment by The-Gig** [comment]
By the way, I notice at some point this map has got a quite noticeable reworking with items. In v3 the upper floor had 3 yellow armors (too many?), now it has none.

**Comment by NeonKnightOA** [comment]
That means there's an error still unsolved. Which armors are you talking about?

**Comment by The-Gig** [comment]
I don't know why this map got such changes after v3... Do you remember if it was Moixie or if it was you?
In v3 the upper floor it had 4 yellow armor and 4 lighning gun. Maybe for some kind if rebalancing some items have been changed and others removed? But some empty recesses look a bit strange...
Maybe comparing v3 and v4 item placement inside Radiant may give some hint about the idea behind the change?

This is from v3:
![Screenshot_20220411-230006](https://user-images.githubusercontent.com/23258514/162832660-deaf4ecd-6006-40b1-a14f-3099a2ea22cf.png)

**Comment by NeonKnightOA** [comment]
Can you open another issue for this? LG is fixed already.

**Comment by The-Gig** [comment]
Yes, my idea was tomorrow to compare entities quantities in v3 and v4 and open an apposite issue about what to do.
