### ISSUE TITLE
OACMPDM7 texture misalignment

### ISSUE THREAD

**Issue by The-Gig** [NeonKnightOA/oacmpvol1#17]
I'm checking old "todo lists" from the forum against z_oacmp1v4_beta-220322.pk3.

OACMPDM7: Small texture misalignment. Here we are on the upper floor. Not important, but still mentioned for completeness.
![shot0227](https://user-images.githubusercontent.com/23258514/161798497-f10cbbb7-eb5f-40fb-8640-86438c3f350e.jpg)

**Comment by NeonKnightOA** [comment]
I don't exactly know how those appear. Guess I'll check.

**Comment by NeonKnightOA** [comment]
More or less fixed.

**Comment by NeonKnightOA** [comment]
https://mega.nz/file/bMZkRJBa#J_rUm2nz2SpiMFl6kBY0eMceeCLOJ1PLfnz_-CQRzCw
New test version.

**Comment by NeonKnightOA** [comment]
Since there were no reports, closing.

**Comment by The-Gig** [comment]
Tried version 20230403, it looks like it's fixed.
