### ISSUE TITLE
About oacmp "mod" folder

### ISSUE THREAD

**Issue by The-Gig** [NeonKnightOA/oacmpvol1#22]
About the "oacmp volume 1 mod" thing (a very simple mod which just mixes oa 0.8.8 and oacmpvol1 maps in a singleplayer campaign), I was thinking that maybe the mod folder could be renamed from "oacmp-mod" to "oacmp1-mod", considering that the future oacmpvol2 mappack might have its own "mod" folder, and that players mixing the mod folders from both mods would not work correctly as the second one would overwrite arenas.txt from the first one.

What do you think about this?

**Comment by NeonKnightOA** [comment]
Well, the oacmp2 mod will definitely have its own folder. That's a given.

**Comment by The-Gig** [comment]
I'd also like to complete oacmp2 after oacmp1, but on the other hand I would prefer to complete _milestone_ mappack before all of its contributors completely leave  Discord. Anyway I guess we can talk about this on Discord.

**Comment by The-Gig** [comment]
I see we already mentioned "oacmp1-mod" in documentation files years ago.
So I went to rename the actual folder, but I was not finding how to rename a folder from github website. Googling revealed to me that by pressing the "." key or changing github.com to github.dev in the url of a repository, you switch to an "editor" which allows things more file-manager-like, such as renaming folders. Mindblowing!
