### ISSUE TITLE
About copying.txt

### ISSUE THREAD

**Issue by The-Gig** [NeonKnightOA/oacmpvol1#23]
Hi, I see with this commit https://github.com/NeonKnightOA/oacmpvol1/commit/7a9b74b08fe523b5c2cd431b48fb3977aa56e524 you deleted the copying.txt file we added some years ago.

That was added _to allow Windows users to actually be able to read it_, as
1) standard "copying" file had no extension so Windows has got no idea of what kind of file it is and hence how to open it. It's possible to manually open it, but it requires some trickery users may not be aware of. The .txt extension fixed the issue;

2) standard "copying" file did contain Linux-style line feed (LF), which classic Windows notepad did not support, showing the file as an extremely long line. Third party editors show properly, but most people stick to default notepad. Maybe Windows 10 and later notepad supports Linux-style carriage return, but I'm not sure (I cannot test now), and howerver older systems are left out. The .txt one was made with Windows-style carriage return (CR-LF).

Thus, if you want to keep only one version of the file, I suggest using the .txt one.

**Comment by The-Gig** [comment]
For the moment I tried converting from linux-style to windows-style a smaller file, oacmp1-mod\readme-oacmp1-mod.txt... (commit https://github.com/NeonKnightOA/oacmpvol1/commit/49e9d30e07a44fcb35596e3020168b361450b70b)
Does it look ok to you?

**Comment by NeonKnightOA** [comment]
Did I do that? Perhaps it was a duplicate. I need to take a look at the docs folder.

**Comment by NeonKnightOA** [comment]
Yep, there was COPYING and COPYING.txt. We don't need two license files that basically say the same thing, so I've deleted one of them.

Here's how the docs folder looked prior to the commit: https://github.com/NeonKnightOA/oacmpvol1/tree/519a8716caa573ecc77c074174c103c231961809/docs

**Comment by The-Gig** [comment]
I agree that we don't need two COPYING files, but of the two I would have kept the Windows-compatible one!
What about swapping them?

**Comment by The-Gig** [comment]
Hi, I tried to be bold and updated some documentations to the Windows-style format.
Do you think it's ok?
https://github.com/NeonKnightOA/oacmpvol1/commit/cdc5e87d1025fb7100595e9ac636c1868a2a30c6
(I used github.dev and first tried to make a pull request out if it instead of pushing directly, but it looks like it doesn't work within the same repository or something, so I had to push. I'm not very good with github stuff.)

**Comment by The-Gig** [comment]
Thank you. I suspected it was something like that. I think before I had write permission on the repository, it created a fork automatically, as it was the only way to make changes for me. Furthermore, probably I didn't know about github.dev back then.

Anyway, I assume your current workflow is just making changes and pushing them, as under "pull requests" I see only some by me in 2017.

**Comment by NeonKnightOA** [comment]
Indeed, that's how I work now.

**Comment by NeonKnightOA** [comment]
Not really important. Closing.
