### ISSUE TITLE
OACMPDM1 very small texture error

### ISSUE THREAD

**Issue by The-Gig** [NeonKnightOA/oacmpvol1#25]
I sent z_oacmp1v4_beta-220322.pk3 to a friend for testing, and he provided me some feedback.

In this case, he found a little mistexurized face under the invisibility item, around coordinates (2024 22 -213) -156.

![shot0040](https://user-images.githubusercontent.com/23258514/162695987-d887f3fc-ca89-47ba-b1f6-b9de7114a825.jpg)

**Comment by EddieBrrrock** [comment]
I think this problem is related to all the "structure like that, I have the same problem with others

**Comment by EddieBrrrock** [comment]
sorry we don't see anything but it is located next to a wall and have a floating shotgun above

**Comment by The-Gig** [comment]
Hi Eddie. Thank you for the feeback, however your screenshots are quite dark. For the future, is it possible for you to make them brighter? The fact that they are in png format makes me think you used OS feature to capture them, maybe using built-in feature (e.g. /bind f12 screenshotjpeg, then pressing the key in-game, then locating them under homepath\baseoa\screenshots) may give brighter results?

**Comment by EddieBrrrock** [comment]
Ok thank you ! I was searching for this because it cause me a lot of problems. I'll try this and edit all my posts to provide better screenshots

**Comment by The-Gig** [comment]
Your screenshots are way more visible now, thank you!

**Comment by NeonKnightOA** [comment]
May just be a lighting problem. I'll try compiling without -dark.

**Comment by NeonKnightOA** [comment]
There's no problem after all. It's a texture lit that way in the angle it was located in.
