### ISSUE TITLE
OACMPDM2 small texture issues

### ISSUE THREAD

**Issue by Bishop-333** [NeonKnightOA/oacmpvol1#30]
![shot0002](https://user-images.githubusercontent.com/99912467/162933080-4c2a4999-94f2-4205-ad8a-f0aac6b00b29.jpg)
This problem happen on only 2/4 angles, others are fine :
![shot0001](https://user-images.githubusercontent.com/99912467/162933129-0d393fff-2a87-4648-86bb-3ffce2ac3372.jpg)

**Comment by The-Gig** [comment]
Good eye!
By the way, when opening "issues" please mention a reference for the version of the package you are testing. I guess you're using z_oacmp1v4_beta-220411.pk3...

**Comment by EddieBrrrock** [comment]
yes it's z_oacmp1v4_beta-220411, I will mention it in my others issues

**Comment by NeonKnightOA** [comment]
https://mega.nz/file/bMZkRJBa#J_rUm2nz2SpiMFl6kBY0eMceeCLOJ1PLfnz_-CQRzCw
New test version. I didn't notice that problem TBH. But I'd rather be sure by letting others test it.

**Comment by NeonKnightOA** [comment]
Since there weren't any reports in almost over a year, closing.

**Comment by The-Gig** [comment]
Tested with version 230430, it looks like it's fixed.
