### ISSUE TITLE
OACMPCTF1 no background music

### ISSUE THREAD

**Issue by The-Gig** [NeonKnightOA/oacmpvol1#42]
OACMPCTF1 lacks background music.
"Music" key in worldspawn entity mentions OA03, but the only background musics in OA 0.8.8 are OA01, OA02, OA06, OA07, OA08, OA13, OA14.

What about OA14 maybe, as it looks like it has not been used in the mappack?

**Comment by NeonKnightOA** [comment]
I'll assign it the same theme as dm5.

**Comment by NeonKnightOA** [comment]
In the end I gave it back its old theme.
