### ISSUE TITLE
OACMPDM2 Dark jumppads

### ISSUE THREAD

**Issue by The-Gig** [NeonKnightOA/oacmpvol1#9]
I'm checking old "todo lists" from the forum against z_oacmp1v4_beta-220322.pk3.

OACMPDM2: Lateral jumppads show this black background.
![shot0215](https://user-images.githubusercontent.com/23258514/161791215-913c1881-8223-4d6e-9edd-d0579ebc20ff.jpg)
.

**Comment by NeonKnightOA** [comment]
Yeah, that wasn't the intended look. Should fix it ASAP.

**Comment by NeonKnightOA** [comment]
Confirmed. Those particular shaders were missing a key line (surfaceparm trans). Fixing.

**Comment by NeonKnightOA** [comment]
In fact, not only the shaders had to be modified, but so the textures as well. Needs testing, if only to squash potential bugs that may appear.

**Comment by NeonKnightOA** [comment]
Indeed, the shaders and textures had to be modified in order to solve this particular issue. The .tga textures became transparent and the shaders were given the right properties.

Once power comes back I'll upload the updated files.

Fixed.

**Comment by The-Gig** [comment]
I tested the new version of the map and I confirm now the background isn't black anymore.
